services:
  - type: web
    name: shruti-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    autoDeploy: true

    envVars:
      - key: API_ID
        value: "21123641"
      - key: API_HASH
        value: "f9f5974d3c0c050964c743c6999ec4e6"
      - key: BOT_TOKEN
        value: "8055188759:AAHbsMNnW0Tf2nrgHrqzevm9MOR2TifUmV0"
      - key: OWNER_ID
        value: "5090115018"
      - key: OWNER_USERNAME
        value: "@Mr_0_Kakashi"
      - key: BOT_USERNAME
        value: "@Darkmension_music_bot"
      - key: MONGO_DB_URI
        value: "mongodb://atlas-sql-690b4fffe997b77184cd8d85-bijdez.a.query.mongodb.net/sample_mflix?ssl=true&authSource=admin"
      - key: LOG_GROUP_ID
        value: "5090115018"
      - key: GIT_TOKEN
        sync: false
      - key: SUPPORT_CHANNEL
        sync: false
      - key: SUPPORT_GROUP
        sync: false
      - key: INSTAGRAM
        sync: false
      - key: YOUTUBE
        sync: false
      - key: GITHUB
        sync: false
      - key: DONATE
        sync: false
      - key: START_IMG_URL
        sync: false
      - key: PING_IMG_URL
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: API_KEY
        sync: false
